# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Core Deploy to IIS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    #dotnet restore, build and publish
    - name: Restore dependencies
      run: dotnet restore
      
     - name: Build
      run: dotnet build --configuration Release .\dotnet-core-github-action
      
    -name: dotnet publish
     run: dotnet publish -c Release -o dotnetcorewebapp .\dotnet-core-github-action
     
     - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./dotnetcorewebapp/* C:/inetpub/wwwroot/dotnet-core-github-action -Recurse -Force
        iisreset /start
   
